language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: reMnmlKpx7EtUwzQ5w/8U1ET/xeJQ4K4/NDKNrRwY2htt2xMeBF0dKp/dpwxSCGMrxm3w9GiARWZDyoodIMqCHD4mbYqxosEmJAgUsG/7qYHLqm3MqwFOcvBQ770PW8tUkp2AMm//ciRMY8kYhokS/2beelC6bLgMv21RBLFdKtINyQe/ejqxhzulQEkRyP9MRcstHCmuIVMQwuZL4k1cr4HLByjs9vAkxTiSbFG8nhbrvE0X0p+q5FpTjLABtRL+095tPvzwfl6WViL/Y00xZYTBf7bDjuicLmQ/idnv9qHlIG2cgigeF/uNDAba4JyJjVSHjboOuA4iTuf/9lyuHg1P1nEZMd+uiNd+bLjFmf5bslmcQLJ1n4XaNJL1G0BLgoHJf7AfnN3n5EA/HVIQ/grP1Ga9HQtY5ryvaPBg0M2NHFS7zbq8T6Bs6HsNjZuOtr23WueftAk/wIhWZ1FwoOAeeFHm/jYj8xggjtolHOw8SQ+S/gnVY2VLzymJPDJxs5fr9a/fCX+ewoZq+QrL/8S3d+n4RoLS7Mo8v9nh9NXtzbs/4EVd8hhmyCaceScicgntuB7cuNgpu5csrssC9Ac+aE1oEHRMhb+vRo9QzqX7sSSTes1wfasPxUuSke97gNN0add8sopgfb/VznKOBU/ZZHg4efvMsZrujouLHo=
  file:
    - 'nlcst-is-literal.js'
    - 'nlcst-is-literal.min.js'
  on:
    tags: true
